src/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path("save_profile/", views.save_profile, name="save_profile"),
    path("reset_password/", views.reset_password, name="reset_password"),
    path("admin_dash/", views.admin_dash, name="admin_dash")
]

src/canary/urls.py
from django.urls import path

from . import views

app_name = "canary"
urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login, name="login"),
    path("dashboard/", views.dashboard, name="dashboard"),

    # urls for notifications
    path("notifications/", views.notifications, name="notifications"),
    path("clear_all_notifications/", views.clear_all_notifications, name="clear_all_notifications"),
    path("delete_notification/", views.delete_notification, name="delete_notification"),
]

src/communities/urls.py
from django.urls import path, re_path
from . import views

app_name = "communities"
urlpatterns = [
    path("create_community/", views.create_community, name="create_community"),
    path("save_community", views.save_community, name="save_community"),
    #path("edit_community/", views.edit_community_redirect, name="edit_community_redirect"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/edit_community/$", views.edit_community_redirect, name="edit_community_redirect"),

    path("edit_community/submit", views.edit_community, name='edit_community'),

    #path("leave_community/", views.leave_community, name="leave_community"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/leave_community/$", views.leave_community, name="leave_community"),


    re_path(r"^(?P<community_id>[0-9a-f-]+)/dashboard/$", views.community_dashboard, name="dashboard"),

    # community joining / leaving
    path("join_community_error/<str:error_type>/", views.join_community_error, name="join_community_error"),
    path("join_success/", views.join_success, name="join_success"),

    # special url for invite links
    re_path(r"^generate_invite/(?P<community_id>[0-9a-f-]+)/$", views.generate_invite_link, name="generate_invite"),
    re_path(r"^invite/(?P<token>[0-9a-f-]+)/$", views.join_community_by_invite, name="join_community_by_invite"),

    # url for submitting anonymously through a link
    re_path(r"^(?P<token>[0-9a-f-]+)/anon_report/", views.create_anonymous_report, name="create_anonymous_report"),

    # urls for report management
    re_path(r"^(?P<community_id>[0-9a-f-]+)/create_report/", views.create_report, name="create_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/save_report/", views.save_report, name="save_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/report/(?P<report_id>[0-9a-f-]+)/$", views.view_report, name="view_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/report/(?P<report_id>[0-9a-f-]+)/edit/", views.edit_report, name="edit_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/report/(?P<report_id>[0-9a-f-]+)/delete/", views.delete_report, name="delete_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/change_admin_status/(?P<member_id>[0-9a-f-]+)/", views.change_admin_status,
            name="change_admin_status"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/remove_member/(?P<member_id>[0-9a-f-]+)/", views.remove_member,
            name="remove_member"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/community_members/", views.community_members, name="community_members"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/make_owner/(?P<member_id>[0-9a-f-]+)/", views.make_owner, name="make_owner"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/save_owner/(?P<member_id>[0-9a-f-]+)/", views.save_owner, name="save_owner"),

]

src/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('canary.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('accounts/', include('accounts.urls')),   
    path('community/', include('communities.urls')),
]

src/templates/dashboard/dash_admin_new.html
{% extends "base.html" %}

{% block content %}
    <h2>Admin Dashboard</h2>
    <p>Welcome to Canary, super powerful admin.</p>
    <p>Here is your dashboard.</p>

{% endblock %}

src/templates/dashboard/dashboard_admin.html
{% extends "base.html" %}

{% block content %}
    <h2>User Dashboard</h2>
    <p>Welcome to Canary, super powerful admin.</p>
    <p>Here is your dashboard.</p>
    <p>Your name: {{ user.first_name }} {{ user.last_name }}</p>
    <p>Your usernam: {{ user.username }}</p>
    <p>Your email: {{user.email }}</p>
    <div class="container mt-5">
        <form method="post" action="{% url 'communities:create_community' %}">
            {% csrf_token %}
            <input type="hidden" name="user_id" value="{{ user.id }}">
            <button type="submit" class="btn btn-primary">Create Community</button>
        </form>
    </div>
{% endblock %}

src/templates/dashboard/dashboard_community_admin.html
{% extends "base.html" %}
{% block content %}
    <h2>Admin Community Home</h2>
    <p>Welcome to Community Home</p>
{% endblock %}

src/templates/dashboard/dashboard_user.html
{% extends "base.html" %}
{% block breadcrumb %}
<nav class="flex py-3 px-5 text-gray-700 bg-gray-600 shadow-lg" aria-label="Breadcrumb">
    <ol class="inline-flex items-center space-x-1 md:space-x-3">
        <li class="inline-flex items-center">
            <a href="{% url 'canary:home' %}"
                class="inline-flex items-center text-sm font-medium text-white hover:text-gray-200">
                <svg aria-hidden="true" class="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z">
                    </path>
                </svg>
                Home
            </a>
        </li>
        <li>
            <div class="flex items-center">
                <svg aria-hidden="true" class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                        clip-rule="evenodd"></path>
                </svg>
                <a href="{% url 'canary:dashboard' %}"
                    class="ml-1 text-sm font-medium text-indigo-400 hover:text-gray-200 md:ml-2">User Dashboard</a>
            </div>
        </li>
    </ol>
</nav>
{% endblock breadcrumb %}
{% block content %}
<div class="container mx-auto py-10">
    <div class="flex justify-center">
        <div class="w-full max-w-2xl">
            <div class="bg-gray-900 shadow-lg rounded-lg overflow-hidden">
                <div class="px-8 py-6 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 text-white">
                    <h2 class="text-3xl font-semibold text-center">User Dashboard</h2>
                    <div class="mt-4 text-center">
                        <p>Your name: {{ user.first_name }} {{ user.last_name }}</p>
                        <p>Your username: {{ user.username }}</p>
                        <p>Your email: {{ user.email }}</p>
                    </div>
                </div>
                <div class="bg-gray-800 px-8 pt-6 pb-8">
                    <div class="flex justify-center mt-4">
                        <form method="post" action="{% url 'communities:create_community' %}">
                            {% csrf_token %}
                            <input type="hidden" name="user_id" value="{{ user.id }}">
                            <button type="submit"
                                class="bg-indigo-400 mb-4 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded transition duration-150 ease-in-out">
                                Create Community
                            </button>
                        </form>
                    </div>
                    {% if admin_communities %}
                    <div class="bg-gray-700 rounded-lg p-4 mb-4">
                        <h3 class="text-xl font-semibold mb-2 text-white">Admin Communities</h3>
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                            {% for community_member in admin_communities %}
                            <a href="{% url 'communities:dashboard' community_member.community.id %}"
                                class="bg-gray-600 border border-gray-500 rounded-lg p-4 text-white hover:bg-gray-500 transition duration-150 ease-in-out">
                                <div class="flex items-center justify-center">
                                    <span
                                        class="inline-block mt-2 text-xl text-blue-400 text-center hover:text-blue-300">
                                        {{ community_member.community.name }}
                                    </span>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                    </div>
                    {% endif %}
                    {% if user_communities %}
                    <div class="bg-gray-700 rounded-lg p-4">
                        <h3 class="text-xl font-semibold mb-2 text-white">Member Communities</h3>
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                            {% for community_member in user_communities %}
                            <a href="{% url 'communities:dashboard' community_member.community.id %}"
                                class="bg-gray-600 border border-gray-500 rounded-lg p-4 text-white hover:bg-gray-500 transition duration-150 ease-in-out">
                                <div class="flex items-center justify-center">
                                    <span
                                        class="inline-block mt-2 text-xl text-blue-400 text-center hover:text-blue-300">
                                        {{ community_member.community.name }}
                                    </span>
                                </div>
                            </a>
                            {% endfor %}
                        </div>
                    </div>
                    {% endif %}
                </div>
                {% if both_empty %}
                <div class="mt-6 text-center text-gray-400">
                    You are not a member of any communities.
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

src/templates/dashboard/dashboard_user_final.html
{% extends "base.html" %}
{% block content %}
<div class="container mx-auto mt-5">
    <div class="flex justify-center">
        <div class="w-full max-w-3xl">
            <h2 class="mb-2 text-xl text-center text-white">User Dashboard</h2>

            {% if both_empty %}
            <p class="pb-4 text-center text-white"> You are not in any communities :( </p>
            {% endif %}

            <!-- outer box  -->
            <div class="bg-lc-900 shadow-md rounded px-8 pt-6 pb-8 mb-4">

                <div class="w-auto h-auto mx-auto flex justify-around">

                    {% if is_super_user %}
                        <div class="mt-5">
                             <form method="post" action="{% url 'accounts:admin_dash' %}">
                             {% csrf_token %}
                                <input type="hidden" name="user_id" value="{{ user.id }}">
                                 <button type="submit"
                                class="bg-gray-500 text-white font-bold py-2 px-4 rounded hover:bg-primary-green hover:text-lc-700 focus:shadow-outline transition duration-150 ease-in-out">
                                Site Admin Dashboard
                            </button>
                        </form>
                        </div>
                    {% endif %}


                    <div class="mt-5">
                        <form method="post" action="{% url 'communities:create_community' %}">
                            {% csrf_token %}
                            <input type="hidden" name="user_id" value="{{ user.id }}">
                            <button type="submit"
                                class="bg-gray-500 text-white font-bold py-2 px-4 rounded hover:bg-primary-green hover:text-lc-700 focus:shadow-outline transition duration-150 ease-in-out">
                                Create Community
                            </button>
                        </form>
                    </div>
                </div>

                {% if not both_empty %}
                <div class="mb-2 pt-6 text-m text-center text-white">Your communities</div>
                {% endif %}

                <div class="grid grid-cols-2">
                    <!-- Column 1 -->
                    <div class="p-4">
                        {% if admin_communities %}
                        <div class="bg-lc-700 shadow-md rounded px-8 pt-6 pb-8 mb-4">
                            <div class="card-body text-white">
                                <p>{{ "Admin" }}</p>
                            </div>
                            {% if admin_communities %}
                            <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                                {% for community_member in admin_communities %}
                                <div class="bg-lc-700 border border-gray-600 rounded-lg p-4 text-white">
                                    <!--<h2>{{ community_member.community.name }}</h2>
                                    <p>{{ community.description }}</p>
                                    -->
                                    <a href="{% url 'communities:dashboard' community_member.community.id %}"
                                        class="text-blue-500 hover:text-blue-800">{{ community_member.community.name }}</a>
                                </div>
                                {% endfor %}
                            </div>
                            {% endif %}
                        </div>
                        {% endif %}
                    </div>
                    <!-- Column 2 -->
                    <div class="p-4">
                        {% if user_communities %}
                        <div class="bg-lc-700 shadow-md rounded px-8 pt-6 pb-8 mb-4">
                            <div class="card-body text-white">
                                <p>{{ "Member" }}</p>
                            </div>
                            {% if user_communities %}
                            <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                                {% for community_member in user_communities %}
                                <div class="bg-lc-700 border border-gray-600 rounded-lg p-4 text-white">
                                    <!--<h2>{{ community_member.community.name }}</h2>
                                    <p>{{ community.description }}</p>
                                    -->
                                    <a href="{% url 'communities:dashboard' community_member.community.id %}"
                                        class="text-blue-500 hover:text-blue-800">{{ community_member.community.name }}</a>
                                </div>
                                {% endfor %}
                            </div>
                            {% endif %}
                        </div>
                        {% endif %}
                    </div>
                </div>

                <!-- outerbox end -->
            </div>

        </div>
    </div>
</div>
{% endblock %}

src/templates/dashboard/new_user_dashboard.html
{% extends "base.html" %}
{% block content %}
<div class="container mx-auto mt-5">
    <h2 class="mb-2 text-xl text-center text-white">User Dashboard</h2>
    <div class="card-body text-white flex justify-center">
        <p>Your name: {{ user.first_name }} {{ user.last_name }}</p>
    </div>
    <div class="card-body text-white flex justify-center">
         <p>Your username: {{ user.username }}</p>
    </div>
    <div class="card-body text-white flex justify-center">
        <p>Your email: {{ user.email }}</p>
    </div>

    <div class="flex justify-center">
        <div class="w-full max-w-md flex">
            <div class="bg-lc-800 shadow-md rounded px-8 pt-6 pb-8 mb-4 w-1/2 pr-2">
                <p>{{ "You are an admin in these communities" }}</p>
                {% if admin_communities %}
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                        {% for community_member in admin_communities %}
                            <div class="bg-lc-700 border border-gray-600 rounded-lg p-4 text-white">
                                <h2>{{ community_member.community.name }}</h2>
                                <p>{{ community.description }}</p>
                                <a href="{% url 'communities:dashboard' community_member.community.id %}"
                                   class="text-xs text-blue-500 hover:text-blue-800">View community</a>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <div class="bg-lc-800 shadow-md rounded px-8 pt-6 pb-8 mb-4 w-1/2 pl-2">
                <p>{{ "You are a member of these communities" }}</p>
                {% if user_communities %}
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                        {% for community_member in user_communities %}
                            <div class="bg-lc-700 border border-gray-600 rounded-lg p-4 text-white">
                                <h2>{{ community_member.community.name }}</h2>
                                <p>{{ community.description }}</p>
                                <a href="{% url 'communities:dashboard' community_member.community.id %}"
                                   class="text-blue-500 hover:text-blue-800">View community</a>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

        </div>

    </div>


    <div class="w-auto h-auto mx-auto flex justify-around">
        <div class="mt-5">
            <form method="post" action="{% url 'communities:create_community' %}">
                {% csrf_token %}
                <input type="hidden" name="user_id" value="{{ user.id }}">
                <button type="submit"
                        class="bg-gray-500 text-white font-bold py-2 px-4 rounded hover:bg-primary-green hover:text-lc-700 focus:shadow-outline transition duration-150 ease-in-out">
                    Create Community
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}