src/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path("save_profile/", views.save_profile, name="save_profile"),
    path("reset_password/", views.reset_password, name="reset_password"),
    path("admin_dash/", views.admin_dash, name="admin_dash")
]

src/canary/urls.py
from django.urls import path

from . import views

app_name = "canary"
urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login, name="login"),
    path("dashboard/", views.dashboard, name="dashboard"),

    # urls for notifications
    path("notifications/", views.notifications, name="notifications"),
    path("clear_all_notifications/", views.clear_all_notifications, name="clear_all_notifications"),
    path("delete_notification/", views.delete_notification, name="delete_notification"),
]

src/communities/urls.py
from django.urls import path, re_path
from . import views

app_name = "communities"
urlpatterns = [
    path("create_community/", views.create_community, name="create_community"),
    path("save_community", views.save_community, name="save_community"),
    #path("edit_community/", views.edit_community_redirect, name="edit_community_redirect"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/edit_community/$", views.edit_community_redirect, name="edit_community_redirect"),

    path("edit_community/submit", views.edit_community, name='edit_community'),

    #path("leave_community/", views.leave_community, name="leave_community"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/leave_community/$", views.leave_community, name="leave_community"),


    re_path(r"^(?P<community_id>[0-9a-f-]+)/dashboard/$", views.community_dashboard, name="dashboard"),

    # community joining / leaving
    path("join_community_error/<str:error_type>/", views.join_community_error, name="join_community_error"),
    path("join_success/", views.join_success, name="join_success"),

    # special url for invite links
    re_path(r"^generate_invite/(?P<community_id>[0-9a-f-]+)/$", views.generate_invite_link, name="generate_invite"),
    re_path(r"^invite/(?P<token>[0-9a-f-]+)/$", views.join_community_by_invite, name="join_community_by_invite"),

    # url for submitting anonymously through a link
    re_path(r"^(?P<token>[0-9a-f-]+)/anon_report/", views.create_anonymous_report, name="create_anonymous_report"),

    # urls for report management
    re_path(r"^(?P<community_id>[0-9a-f-]+)/create_report/", views.create_report, name="create_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/save_report/", views.save_report, name="save_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/report/(?P<report_id>[0-9a-f-]+)/$", views.view_report, name="view_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/report/(?P<report_id>[0-9a-f-]+)/edit/", views.edit_report, name="edit_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/report/(?P<report_id>[0-9a-f-]+)/delete/", views.delete_report, name="delete_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/change_admin_status/(?P<member_id>[0-9a-f-]+)/", views.change_admin_status,
            name="change_admin_status"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/remove_member/(?P<member_id>[0-9a-f-]+)/", views.remove_member,
            name="remove_member"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/community_members/", views.community_members, name="community_members"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/make_owner/(?P<member_id>[0-9a-f-]+)/", views.make_owner, name="make_owner"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/save_owner/(?P<member_id>[0-9a-f-]+)/", views.save_owner, name="save_owner"),

]

src/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('canary.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('accounts/', include('accounts.urls')),   
    path('community/', include('communities.urls')),
]

src/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en" class="h-full">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}Canary{% endblock %}
    </title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/canary.svg' %}">
    <link href="{% static 'output.css' %}" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.1.2/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/index.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@2.8.2/dist/alpine.js" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/vanilla-tilt@1.7.0"></script>
    <style>
        /* Hide scrollbar for all browsers */

        /* Firefox */
        body {
            scrollbar-width: none;
        }

        /* Webkit (Chrome, Safari) */
        body::-webkit-scrollbar {
            display: none;
        }

        /* IE and Edge */
        body {
            -ms-overflow-style: none;
            /* Hides the scrollbar in IE 10+ */
        }
    </style>
</head>

<body class="flex flex-col min-h-screen bg-gray-900 text-color">
    <header>
        <nav class="bg-gray-800">
            <div class="display-none m-auto h-[50px] w-full items-center justify-between px-6 md:flex max-w-[1200px]">
                <div class="hidden md:flex items-center gap-2">
                    <img src="{% static 'images/canary.svg' %}" alt="Canary Logo" width="30" height="30">
                    {% if user.is_authenticated %}
                    <a class="text-orange-800 text-lg font-semibold" href="{% url 'canary:dashboard' %}">Canary</a>
                    {% else %}
                    <a class="text-orange-800 text-lg font-semibold" href="/">Canary</a>
                    {% endif %}

                </div>
                <div class="flex items-center gap-4">
                    {% if user.is_authenticated %}
                    <a href="{% url 'canary:notifications'%}">
                        <div
                            class="relative inline-flex items-center rounded-full border border-gray-600 hover:bg-orange-400 p-2">
                            {% if notifications_count > 0 %}
                            <span
                                class="absolute top-0 right-0 h-4 w-4 rounded-full bg-red-600 text-white flex justify-center items-center text-xs">
                                {% if notifications_count > 9 %}
                                9+
                                {% else %}
                                {{ notifications_count }}
                                {% endif %}
                            </span>
                            {% endif %}
                            <svg class="h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                                fill="currentColor">
                                <path
                                    d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z" />
                            </svg>
                        </div>
                    </a>
                    <div x-data="{ open: false }" class="relative">
                        <button @click="open = !open" class="flex items-center focus:outline-none text-text-color">
                            {{ user.username }}
                            <svg fill="none" stroke="currentColor" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M19 9l-7 7-7-7"></path>
                            </svg>
                        </button>
                        <div x-show="open" @click.away="open = false"
                            class="absolute right-0 mt-2 py-2 w-48 bg-gray-600 rounded-md shadow-xl z-20">
                            <!-- href="{% url 'account_email' %}"
                                class="block px-4 py-2 text-sm text-white hover:bg-gray-100 hover:text-gray-600">Change
                                Email</-->
                            <a href="{% url 'accounts:edit_profile' %}"
                                class="block px-4 py-2 text-sm text-white hover:bg-gray-100 hover:text-gray-600">Edit
                                Profile</a>
                            <a href="{% url 'account_logout' %}"
                                class="block px-4 py-2 text-sm text-white hover:bg-gray-100 hover:text-gray-600">Sign
                                Out</a>
                        </div>
                    </div>
                    {% else %}
                    <a href="{% url 'account_login' %}"
                        class="text-text-color px-4 py-2 hover:bg-orange-400 rounded">Login</a>
                    <a href="{% url 'account_signup' %}"
                        class="text-text-color px-4 py-2 hover:bg-orange-400 rounded">Sign up</a>
                    <a href="{% url 'account_reset_password' %}"
                        class="text-text-color px-4 py-2 hover:bg-orange-400 rounded">Forgot Password</a>
                    {% endif %}
                </div>
            </div>
        </nav>
        {% block breadcrumb %}
        {% endblock breadcrumb %}
    </header>
    <div class="bg-gray-900 mx-auto w-full flex-grow p-4 md:max-w-[888px] md:p-6 lg:max-w-screen-xl">
        {% block body %}
        {% if messages %}
        {% for message in messages %}
        <div class="toast border-t border-b border-blue-500 text-blue-700 px-4 py-3 bg-blue-50 animate-slideIn
                    rounded-lg shadow-lg max-w-lg mx-auto mt-5" role="alert" data-toast-id="{{ forloop.counter }}">
            <div class="flex justify-between items-center">
                <strong class="font-bold">{% trans "Messages:" %}</strong>
                <button type="button" class="toast-close text-blue-700" data-toast-id="{{ forloop.counter }}">
                    <span class="text-2xl">&times;</span>
                </button>
            </div>
            <ul class="list-disc pl-5 mt-2">
                <li>{{ message }}</li>
            </ul>
        </div>
        {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock content %}
        {% block scripts %}
        {% endblock scripts %}
        {% endblock body %}
        {% block extra_body %}
        {% endblock extra_body %}
    </div>
    <script src="{% static 'tw-elements/js/tw-elements.umd.min.js' %}" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js"></script>
    <script>
        document.addEventListener( 'DOMContentLoaded', ( event ) => {
            document.querySelectorAll( '.toast-close' ).forEach( button => {
                button.addEventListener( 'click', function ( e ) {
                    const toastId = this.getAttribute( 'data-toast-id' );
                    const toastElement = document.querySelector( `[data-toast-id="${toastId}"]` );
                    if ( toastElement ) {
                        toastElement.style.display = 'none';
                    }
                } );
            } );
        } );
    </script>
    <footer class="mt-auto bg-gray-800 shadow dark:bg-gray-800">
        <div class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
            <span class="text-sm text-white sm:text-center dark:text-gray-400">© 2024 <a
                    href="https://b17-s24-asd-f1f7ff7a2336.herokuapp.com/" class="hover:underline">Canary™</a>All Rights
                Reserved.</span>
            <span class="text-sm text-white"><a>Disclaimer: This is a class project and should not be used for
                    real-world
                    applications.</a></span>
        </div>
    </footer>
</body>

</html>

src/templates/create-community.html
{% extends "base.html" %}

{% block content %}
    <div class="container mt-5">
        <form method="post" action="{% url 'communities:save_community' %}">
            {% csrf_token %}
            <div class="mb-3">
                <label for="name" class="form-label">Community Name:</label>
                <input type="text" class="form-control" id="name" name="name" required>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label"> Community Password:</label>
                <input type="text" class="form-control" id="password" name="password" required>
            </div>
            <div class="mb-3">
                <label for="description" class="form-label"> Community Description:</label>
                <input type="text" class="form-control" id="description" name="description" required>
            </div>
            <button type="submit" class="btn btn-primary">Submit Community</button>
        </form>
    </div>
{% endblock %}

src/templates/home.html
{% extends "base.html" %}
{% load static %} <!-- Django tag to load static files -->
{% block content %}
<div class="container mx-auto mt-10 text-center">
    <div class="bg-red-500 text-white p-4 font-bold text-center">
        Disclaimer: This is a class project and should not be used for real-world applications.
    </div>
    <h1 class="text-4xl font-bold text-white mb-4">Welcome to Canary</h1>
    <p class="text-lg text-gray-200 mb-4">
        Canary is a vibrant community where you get to snitch without getting stitches (here's hoping).
    </p>
    <!-- SVG Container with Tilt and Gradient Glare Effect -->
    <div id="svg-tilt-container" class="tilt" data-tilt data-tilt-max="25" data-tilt-scale="1.1" data-tilt-speed="400"
        data-tilt-perspective="500">
        <img src="{% static 'images/shushing-face-svgrepo-com.svg' %}" alt="Shushing Face" width="200" height="200">
        <div class="glare-gradient"></div>
    </div>
    <div class="flex justify-center mt-8">
        <a href="{% url 'account_signup' %}"
            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-4">Join Now</a>
        <a href="{% url 'account_login' %}"
            class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded">Log In</a>
    </div>
</div>
<script>
    document.addEventListener( 'DOMContentLoaded', function () {
        VanillaTilt.init( document.querySelector( "#svg-tilt-container" ), {
            max: 25,
            speed: 400,
            glare: true,
            "max-glare": 0.5
        } );
    } );
</script>
<style>
    #svg-tilt-container {
        position: relative;
        width: 300px;
        height: 300px;
        margin: 20px auto;
        display: flex;
        justify-content: center;
        align-items: center;
        transform-style: preserve-3d;
        transition: ease width 0.3s
    }

    #svg-tilt-container .glare-gradient {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        mix-blend-mode: overlay;
        pointer-events: none;
    }

    #svg-tilt-container:hover {
        margin-top: 2rem;
        margin-bottom: 2rem;
        background: linear-gradient(45deg, #667eea, #764ba2, #ff758c);
        width: 350px;

    }


    #svg-tilt-container img {
        transform: translateZ(20px);
        z-index: 1;
    }
</style>
{% endblock %}

src/templates/notifications.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="bg-gray-900 py-8">
    <div class="max-w-5xl mx-auto bg-gray-800 rounded-lg shadow-md overflow-hidden">
        <div class="py-4 px-6 bg-orange-600 text-white flex justify-between items-center">
            <h2 class="text-2xl font-bold">Notifications</h2>
            <form method="post" action="{% url 'canary:clear_all_notifications' %}">
                {% csrf_token %}
                <button type="submit"
                    class="bg-indigo-400 text-white font-semibold py-2 px-4 rounded hover:bg-indigo-600 transition-colors duration-300">
                    Clear All Notifications
                </button>
            </form>
        </div>
        <div class="divide-y divide-gray-700">
            {% for notif, is_viewed in notifications.items %}
            <div class="py-4 px-6 hover:bg-gray-700 transition-colors duration-300 flex justify-between items-center">
                <div class="flex items-center">
                    <span class="text-gray-300 mr-2">
                        {% if not is_viewed %}
                        <svg class="w-4 h-4 text-orange-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                            fill="currentColor">
                            <path fill-rule="evenodd"
                                d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                                clip-rule="evenodd" />
                        </svg>
                        {% endif %}
                    </span>
                    <a class="text-gray-300 hover:text-orange-400 transition-colors duration-300"
                        href="{% url 'communities:dashboard' notif.community.id %}">{{ notif.content }}</a>
                </div>
                <form method="post" action="{% url 'canary:delete_notification' %}">
                    {% csrf_token %}
                    <input type="hidden" name="notif_id" value="{{ notif.id }}">
                    <button type="submit"
                        class="bg-red-600 text-white font-semibold py-2 px-4 rounded hover:bg-red-700 transition-colors duration-300">
                        Clear
                    </button>
                </form>
            </div>
            {% empty %}
            <div class="py-4 px-6 text-gray-400">
                No notifications
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

src/templates/password_reset.html
{% extends "base.html" %}
{% block content %}
    <div class="min-h-screen flex flex-col justify-center items-center bg-gray-100">
        <div class="max-w-md w-full bg-white rounded-lg shadow-md p-6 space-y-4">
            <h2 class="text-center text-2xl font-bold text-gray-900">Forgot Password</h2>
            <form method="post" class="mt-8 space-y-6">
                {% csrf_token %}
                <div class="rounded-md shadow-sm -space-y-px">{{ form.as_p }}</div>
                <div>
                    <button type="submit"
                            class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        Reset password
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

src/templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="min-h-screen flex flex-col justify-center items-center bg-gray-100">
    <div class="max-w-md w-full bg-white rounded-lg shadow-md p-6 space-y-6">
        <h2 class="text-center text-2xl font-bold text-gray-900">Sign up</h2>
        <form method="post" class="space-y-4">
            {% csrf_token %}
            <div class="rounded-md shadow-sm -space-y-px">
                {{ form.as_p }}
            </div>
            <div>
                <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    Sign up
                </button>
            </div>
        </form>
        <div class="flex items-center justify-center">
            <div class="text-sm">
                <p class="text-gray-600">Or</p>
            </div>
        </div>
        <div>
            <a href="{% provider_login_url 'google' %}" class="w-full flex justify-center py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50">
                Sign up with Google
            </a>
        </div>
    </div>
</div>
{% endblock %}