src/canary/urls.py
from django.urls import path

from . import views

app_name = "canary"
urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login, name="login"),
    path("dashboard/", views.dashboard, name="dashboard"),

    # urls for notifications
    path("notifications/", views.notifications, name="notifications"),
    path("clear_all_notifications/", views.clear_all_notifications, name="clear_all_notifications"),
    path("delete_notification/", views.delete_notification, name="delete_notification"),
]

src/communities/urls.py
from django.urls import path, re_path
from . import views

app_name = "communities"
urlpatterns = [
    path("create_community/", views.create_community, name="create_community"),
    path("save_community", views.save_community, name="save_community"),
    #path("edit_community/", views.edit_community_redirect, name="edit_community_redirect"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/edit_community/$", views.edit_community_redirect, name="edit_community_redirect"),

    path("edit_community/submit", views.edit_community, name='edit_community'),

    #path("leave_community/", views.leave_community, name="leave_community"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/leave_community/$", views.leave_community, name="leave_community"),


    re_path(r"^(?P<community_id>[0-9a-f-]+)/dashboard/$", views.community_dashboard, name="dashboard"),

    # community joining / leaving
    path("join_community_error/<str:error_type>/", views.join_community_error, name="join_community_error"),
    path("join_success/", views.join_success, name="join_success"),

    # special url for invite links
    re_path(r"^generate_invite/(?P<community_id>[0-9a-f-]+)/$", views.generate_invite_link, name="generate_invite"),
    re_path(r"^invite/(?P<token>[0-9a-f-]+)/$", views.join_community_by_invite, name="join_community_by_invite"),

    # url for submitting anonymously through a link
    re_path(r"^(?P<token>[0-9a-f-]+)/anon_report/", views.create_anonymous_report, name="create_anonymous_report"),

    # urls for report management
    re_path(r"^(?P<community_id>[0-9a-f-]+)/create_report/", views.create_report, name="create_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/save_report/", views.save_report, name="save_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/report/(?P<report_id>[0-9a-f-]+)/$", views.view_report, name="view_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/report/(?P<report_id>[0-9a-f-]+)/edit/", views.edit_report, name="edit_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/report/(?P<report_id>[0-9a-f-]+)/delete/", views.delete_report, name="delete_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/change_admin_status/(?P<member_id>[0-9a-f-]+)/", views.change_admin_status,
            name="change_admin_status"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/remove_member/(?P<member_id>[0-9a-f-]+)/", views.remove_member,
            name="remove_member"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/community_members/", views.community_members, name="community_members"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/make_owner/(?P<member_id>[0-9a-f-]+)/", views.make_owner, name="make_owner"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/save_owner/(?P<member_id>[0-9a-f-]+)/", views.save_owner, name="save_owner"),

]

src/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('canary.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('accounts/', include('accounts.urls')),   
    path('community/', include('communities.urls')),
]

src/communities/models.py
from django.db import models
import uuid
from django.utils import timezone
from django.contrib.auth import get_user_model
# Create your models here.


# main community model
class Community(models.Model):
    #class Meta:
        #app_label = 'communities'

    # each community has a unique id
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)

    description = models.TextField(blank=False, max_length=500)

    # each community stores a list of reports submitted to that community
    reports = models.ManyToManyField('Report')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

# invite link model
class InviteLink(models.Model):
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    token = models.UUIDField(default=uuid.uuid4, editable=False)
    expiration_time = models.DateTimeField()
    # max uses for link, 0 means unlimited
    max_uses = models.IntegerField(default=0)
    used_count = models.IntegerField(default=0)
    link_type = models.CharField(max_length=4, default='join') # join or anon for now

    def is_valid(self):
        return (self.used_count < self.max_uses or self.max_uses == 0) and self.expiration_time > timezone.now()

# community member relational model
class CommunityMember(models.Model):
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    member = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    is_admin = models.BooleanField(default=False)
    is_owner = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.member} in {self.community}'

# --- REPORT MODELS ----

# report model
class Report(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100, blank=False)
    content = models.TextField(max_length=2000, blank=True)

    # the author user is optional (for anonymous reports)
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True)

    # users can specify how the report is handled from a few options
    class ResolutionMethod(models.TextChoices):
        CANARY = 'CAN', 'Canary'
        EXTERNALLY = 'EXT', 'Externally'
        NO_CONTACT = 'NOC', 'No Contact'

    resolution_method = models.CharField(
        max_length=3,
        choices=ResolutionMethod.choices,
        default=ResolutionMethod.CANARY,
    )

    # reports have a status, either "New", "In Progress", or "Resolved"
    class Status(models.TextChoices):
        NEW = 'NEW', 'New'
        IN_PROGRESS = 'INP', 'In Progress'
        RESOLVED = 'RES', 'Resolved'

    status = models.CharField(
        max_length=3,
        choices=Status.choices,
        default=Status.NEW,
    )

    # reports have a large text field for notes added by an admin
    notes = models.TextField(blank=True, max_length=2000)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title


class UploadedFile(models.Model):
    file = models.FileField(upload_to='uploads/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    # each file is associated with a report
    report = models.ForeignKey(Report, on_delete=models.CASCADE)

    def __str__(self):
        return self.file.name

src/communities/forms.py
from django import forms

class InviteForm(forms.Form):
    expiration = forms.ChoiceField(choices=[
        ('1h', '1 Hour'),
        ('1d', '1 Day'),
        ('1w', '1 Week'),
        ('1m', '1 Month'),
        ('never', 'Never')
    ])
    max_uses = forms.NumberInput()

src/communities/views.py
import json
import re

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils import timezone

from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from .models import Community, CommunityMember, Report, UploadedFile, InviteLink
from django.urls import reverse
from canary.views import new_report_notif, report_status_notif, report_notes_notif


# helper method to ensure user is able to view the community/report they are trying to access
# silently redirects to their user dashboard if not
def check_user_access(request, page_type, level='member', community_id=None, report_id=None):
    if not request.user.is_authenticated:
        return False

    if page_type == 'community':
        community = get_object_or_404(Community, pk=community_id)
        if not CommunityMember.objects.filter(community=community, member=request.user).exists():
            return False
    elif page_type == 'report':
        community = get_object_or_404(Community, pk=community_id)
        report = get_object_or_404(Report, pk=report_id)
        if not CommunityMember.objects.filter(community=community, member=request.user, is_admin=True).exists()\
                and not report.author == request.user:
            return False

    if level == 'admin':
        community = get_object_or_404(Community, pk=community_id)
        if not CommunityMember.objects.filter(community=community, member=request.user, is_admin=True).exists():
            return False
    elif level == 'owner':
        community = get_object_or_404(Community, pk=community_id)
        if not CommunityMember.objects.filter(community=community, member=request.user, is_owner=True).exists():
            return False

    return True


def create_community(request):
    return render(request, 'community/create_community.html')


def edit_community_redirect(request, community_id):
    return render(request, 'community/edit_community.html', context={'community_id': community_id})


@login_required
def edit_community(request):

    # make sure the user is a community admin
    if not check_user_access(request, 'community', community_id=request.POST.get('community_id'), level='admin'):
        return HttpResponseRedirect(reverse("canary:dashboard"))

    community = get_object_or_404(
        Community, pk=request.POST.get('community_id'))
    new_description = request.POST.get('community_description')
    new_name = request.POST.get('community_name')

    # validate the new info
    if re.match(r"^\s*$", new_name) or len(new_name) > 50:
        messages.error(request, 'Invalid community name. Please try again.')
        return HttpResponseRedirect(reverse("communities:edit_community_redirect", args=[community.id]))
    if re.match(r"^\s*$", new_description) or len(new_description) > 500:
        messages.error(
            request, 'Invalid community description. Please try again.')
        return HttpResponseRedirect(reverse("communities:edit_community_redirect", args=[community.id]))

    community.description = new_description
    community.name = new_name
    community.updated_at = timezone.now()
    community.save()
    return redirect('communities:dashboard', community_id=request.POST.get('community_id'))


def leave_community(request, community_id):
    community = get_object_or_404(Community, pk=community_id)
    user_id = request.POST.get('user_id')
    CommunityMember.objects.filter(
        community=community, member=request.user).delete()
    return redirect('canary:dashboard')


@login_required
def community_dashboard(request, community_id):

    # make sure the user is a community member
    if not check_user_access(request, 'community', community_id=community_id):
        return HttpResponseRedirect(reverse("canary:dashboard"))

    # get the community object
    community = get_object_or_404(Community, pk=community_id)

    # get the community members
    members = CommunityMember.objects.filter(community=community)

    is_admin = False
    # get the reports submitted to the community if admin, else only get reports submitted by the user
    if CommunityMember.objects.get(community=community, member=request.user).is_admin:
        reports = community.reports.all()
        is_admin = True
    else:
        reports = Report.objects.filter(
            community=community, author=request.user)

    return render(request, 'community/community_dashboard.html', {'community': community, 'members': members, 'reports': reports, 'is_admin': is_admin, 'community_id': community_id})


def join_community_by_invite(request, token):
    try:
        invite_link = InviteLink.objects.get(token=token)
        if invite_link.is_valid():
            # Log in the user if not already logged in
            if not request.user.is_authenticated:
                return render(request, 'account/login.html')

            # Check if the user is already a member of the community
            if CommunityMember.objects.filter(community=invite_link.community, member=request.user).exists():
                messages.success(
                    request, 'You are already a member of this community.')
                return redirect('communities:dashboard', community_id=invite_link.community.id)

            # Add the user to the community
            CommunityMember.objects.create(
                community=invite_link.community, member=request.user)

            # Update the used count of the invite link
            invite_link.used_count += 1
            invite_link.save()

            # Redirect to join success page
            return redirect('communities:join_success')
        else:
            # delete the expired invite link
            # Redirect to error page for expired or invalid link
            return redirect('communities:join_community_error', error_type='invalid_link')
    except InviteLink.DoesNotExist:
        # Redirect to error page if invite link does not exist
        return redirect('communities:join_community_error', error_type='invalid_link')


def generate_invite_link(request, community_id):

    # if the user is not logged in, redirect to the site home page
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("canary:"))

    # make sure the user is a community admin
    if not check_user_access(request, 'community', community_id=community_id, level='admin'):
        return HttpResponseRedirect(reverse("canary:dashboard"))

    # get properties from request
    body = json.loads(request.body)
    expiration = body['expiration']
    max_uses = body['num_invites']
    link_type = body['link_type']

    # expiration is either '1h', '1d', '1w', '1m', or 'never'
    match expiration:
        case '1h':
            expiration_time = timezone.now() + timezone.timedelta(hours=1)
        case '1d':
            expiration_time = timezone.now() + timezone.timedelta(days=1)
        case '1w':
            expiration_time = timezone.now() + timezone.timedelta(weeks=1)
        case '1m':
            expiration_time = timezone.now() + timezone.timedelta(weeks=4)
        case 'never':
            expiration_time = timezone.now() + timezone.timedelta(weeks=52)

    if max_uses == '':
        max_uses = 1

    # generate a new invite link
    invite_link = InviteLink(community_id=community_id,
                             expiration_time=expiration_time, max_uses=max_uses, link_type=link_type)
    invite_link.save()

    # create the actual link
    if link_type == 'join':
        # url pattern: invite/<UUID:token>/
        link_str = reverse("communities:join_community_by_invite", args=[
                           str(invite_link.token)])
    elif link_type == 'anon':
        # url pattern: community/<UUID:community_id>/anon_report/
        link_str = reverse("communities:create_anonymous_report", args=[
                           str(invite_link.token)])
    else:
        return HttpResponse(json.dumps({'error': 'Invalid link type'}), content_type='application/json', status=400)

    # return a response with invite link token and request headers
    return HttpResponse(json.dumps({'invite_link': link_str}), content_type='application/json')


def join_community_error(request, error_type):
    return render(request, 'community/join_community_error.html', {'error_type': error_type})


def join_success(request):
    return render(request, 'community/join_success.html')


@login_required
def community_members(request, community_id):

    # make sure the user has access to the community
    if not check_user_access(request, 'community', community_id=community_id):
        return HttpResponseRedirect(reverse("canary:dashboard"))

    # Get the community object or return 404 if not found
    community = get_object_or_404(Community, id=community_id)
    # Retrieve community members for the specified community
    community_member = CommunityMember.objects.filter(community=community)

    # get the permission level of the current user
    user_member = CommunityMember.objects.get(
        community=community, member=request.user)

    user_role = 'owner' if user_member.is_owner else 'admin' if user_member.is_admin else 'member'

    # can the user remove members?
    can_remove = user_member.is_owner or user_member.is_admin

    # Pass the community_members data to the template
    return render(request, 'community/community_members.html', {'community_id': community_id, 'community_member': community_member, 'user_role': user_role, 'can_remove': can_remove})


@login_required
def make_owner(request, community_id, member_id):
    # make sure the user has access to the community
    if not check_user_access(request, 'community', level='owner', community_id=community_id):
        return HttpResponseRedirect(reverse("canary:dashboard"))

src/templates/community/community_members.html
{% extends "base.html" %}
{% block breadcrumb %}
<nav class="flex py-3 px-5 text-gray-700 bg-gray-600 shadow-lg" aria-label="Breadcrumb">
    <ol class="inline-flex items-center space-x-1 md:space-x-3">
        <li class="inline-flex items-center">
            <a href="{% url 'canary:home' %}"
                class="inline-flex items-center text-sm font-medium text-white hover:text-gray-200">
                <svg aria-hidden="true" class="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z">
                    </path>
                </svg>
                Home
            </a>
        </li>
        <li>
            <div class="flex items-center">
                <svg aria-hidden="true" class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                        clip-rule="evenodd"></path>
                </svg>
                <a href="{% url 'canary:dashboard' %}"
                    class="ml-1 text-sm font-medium text-white hover:text-gray-200 md:ml-2">User Dashboard</a>
            </div>
        </li>
        <li>
            <div class="flex items-center">
                <svg aria-hidden="true" class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                        clip-rule="evenodd"></path>
                </svg>
                <a href="{% url 'communities:dashboard' community_id %}"
                    class="ml-1 text-sm font-medium text-indigo-400 hover:text-gray-200 md:ml-2">Community Dashboard</a>
            </div>
        </li>
    </ol>
</nav>
{% endblock breadcrumb %}
{% block content %}
<div class="bg-gray-900 mt-4 flex items-center justify-center overflow-scroll" xmlns="http://www.w3.org/1999/html">
    <div class="w-full max-w-5xl bg-gray-800 shadow-md rounded-lg overflow-scroll p-6">
        <div class="mb-6">
            <h1 class="text-3xl font-bold m-2 text-gray-100">Community Members</h1>
        </div>
        <div class="bg-gray-700 rounded-lg">
            <ul class="divide-y divide-gray-600">
                {% for member in community_member %}
                <li
                    class="py-3 px-4 flex justify-between items-center {% if member.member.email == user.email %}bg-gray-600{% endif %}">
                    <div class="flex gap-2 justify-center items-center">
                        <div class="text-gray-300 hover:text-white transition-colors">
                            {{ member.member.username }}
                        </div>
                        {% if member.is_owner %}
                        <span class="bg-red-500 text-white text-xs font-semibold px-2.5 py-0.5 rounded">Owner</span>
                        {% elif member.is_admin %}
                        <span class="bg-blue-500 text-white text-xs font-semibold px-2.5 py-0.5 rounded">Admin</span>
                        {% else %}
                        <span class="bg-gray-500 text-white text-xs font-semibold px-2.5 py-0.5 rounded">Member</span>
                        {% endif %}
                    </div>
                    <div class="flex items-center space-x-2">
                        <div class="px-2 py-1">
                            {% if can_remove and not member.is_admin %}
                            <form method="post"
                                action="{% url 'communities:remove_member' community_id member.member.id %}"
                                enctype="multipart/form-data" class="inline-block">
                                {% csrf_token %}
                                <input type="hidden" name="user_id" value="{{ user.id }}">
                                <button type="submit"
                                    class="bg-red-600 text-white text-sm py-1 px-4 rounded hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-opacity-50 transition duration-150 ease-in-out">Remove</button>
                            </form>
                            {% endif %}
                            {% if user_role == 'owner' %}
                            <form method="post"
                                action="{% url 'communities:change_admin_status' community_id member.member.id %}"
                                enctype="multipart/form-data" class="inline-block">
                                {% csrf_token %}
                                <input type="hidden" name="user_id" value="{{ user.id }}">
                                {% if member.is_admin %}
                                {% if member.is_owner %}
                                    <a href="{% url 'communities:make_owner' community_id member.member.id %}"
                                        class="bg-blue-500 text-white text-sm py-1 px-4 rounded hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 transition duration-150 ease-in-out">Make New Owner </a>
                                {% else %}<button type="submit"
                                    class="bg-yellow-500 text-white text-sm py-1 px-4 rounded hover:bg-yellow-600 focus:outline-none focus:ring-2 focus:ring-yellow-500 focus:ring-opacity-50 transition duration-150 ease-in-out">Demote</button>{% endif %}
                                {% else %}
                                <button type="submit"
                                    class="bg-green-600 text-white text-sm py-1 px-4 rounded hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 transition duration-150 ease-in-out">Promote</button>
                                {% endif %}
                            </form>
                            {% endif %}
                        </div>
                    </div>
                </li>

                {% empty %}
                <li class="py-3= px-4 text-gray-300">No members in this community yet.</li>
                {% endfor %}
            </ul>
        </div>

        <a href="{% url 'communities:dashboard' community_id %}"
            class="bg-indigo-400 hover:bg-indigo-600 mt-8 text-white font-bold py-2 px-4 rounded inline-flex items-center">
            Go Back
        </a>
    </div>
</div>
{% endblock %}

src/templates/community/create_community.html
{% extends "base.html" %}
{% block breadcrumb %}
<nav class="flex py-3 px-5 text-gray-700 bg-gray-600 shadow-lg" aria-label="Breadcrumb">
    <ol class="inline-flex items-center space-x-1 md:space-x-3">
        <li class="inline-flex items-center">
            <a href="{% url 'canary:home' %}"
                class="inline-flex items-center text-sm font-medium text-white hover:text-gray-200">
                <svg aria-hidden="true" class="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z">
                    </path>
                </svg>
                Home
            </a>
        </li>
        <li>
            <div class="flex items-center">
                <svg aria-hidden="true" class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                        clip-rule="evenodd"></path>
                </svg>
                <a href="{% url 'canary:dashboard' %}"
                    class="ml-1 text-sm font-medium text-indigo-400 hover:text-gray-200 md:ml-2">User Dashboard</a>
            </div>
        </li>
    </ol>
</nav>
{% endblock breadcrumb %}
{% block content %}
<div class="container mx-auto py-10">
    <div class="flex justify-center">
        <div class="w-full max-w-2xl">
            <div class="bg-gray-900 shadow-lg rounded-lg overflow-hidden">
                <div class="px-8 py-6 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 text-white">
                    <h2 class="text-3xl font-semibold text-center">Create a Community</h2>
                    <form method="post" action="{% url 'communities:save_community' %}"
                        class="bg-lc-200 border border-2 bg-opacity-5 drop-shadow-lg px-8 pt-6 pb-8 mt-4">
                        {% csrf_token %}
                        <div class="mb-4">
                            <label for="name" class="block text-white font-bold mb-2">Community Name:</label>
                            <input type="text"
                                class="shadow appearance-none border rounded w-full py-2 px-3 text-white bg-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                                id="name" name="name" required>
                        </div>
                        <div class="mb-4">
                            <label for="description" class="block text-white font-bold mb-2">Community
                                Description:</label>
                            <input type="text"
                                class="shadow appearance-none border rounded w-full py-2 px-3 text-white bg-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                                id="description" name="description" required>
                        </div>
                        <input type="hidden" name="user_id" value="{{ user.id }}">
                        <button type="submit"
                            class="bg-indigo-400 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded transition duration-150 ease-in-out">
                            Submit Community
                        </button>
                        <a href="{% url 'canary:dashboard' %}"
                            class="bg-indigo-400 ml-7 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded duration-150 ease-in-out inline-block">
                            Go Back
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/community/make_owner.html
{% extends "base.html" %}

{% block content %}
<div class="bg-gray-900 mt-4 flex items-center justify-center">
    <div class="w-full max-w-5xl bg-gray-800 shadow-md rounded-lg overflow-hidden p-6">
        <div class="mb-6">
            <h1 class="text-3xl font-bold text-gray-100">Community Members</h1>
        </div>
        <div class="bg-gray-700 rounded-lg">
            <ul class="divide-y divide-gray-600">
                {% for member in community_member %}
                <li class="py-3 px-4 flex justify-between items-center {% if member.member.email == user.email %}bg-gray-600{% endif %}">
                    <div class="flex items-center">
                        <div class="text-gray-300 hover:text-white transition-colors">
                            {{ member.member.username }}
                        </div>
                    </div>
                    <div class="flex items-center space-x-2">
                        {% if member.is_owner %}
                        <span class="bg-red-500 text-white text-xs font-semibold px-2.5 py-0.5 rounded">Owner</span>
                        {% elif member.is_admin %}
                        <span class="bg-blue-500 text-white text-xs font-semibold px-2.5 py-0.5 rounded">Admin</span>
                        {% else %}
                        <span class="bg-gray-500 text-white text-xs font-semibold px-2.5 py-0.5 rounded">Member</span>
                        {% endif %}
                        {% if user_role == 'owner' and not member.is_owner %}
                        <form method="post" action="{% url 'communities:save_owner' community_id member.member.id %}"
                            enctype="multipart/form-data" class="inline-block">
                            {% csrf_token %}
                            <input type="hidden" name="user_id" value="{{ user.id }}">
                            <button type="submit"
                                class="bg-blue-500 text-white text-sm py-1 px-4 rounded hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 transition duration-150 ease-in-out">Make Owner</button>
                        </form>
                        {% endif %}
                    </div>
                </li>
                {% empty %}
                <li class="py-3 px-4 text-gray-300">No members in this community yet.</li>
                {% endfor %}
            </ul>
        </div>

        <a href="{% url 'communities:dashboard' community_id %}"
            class="bg-blue-500 hover:bg-blue-700 mt-8 text-white font-bold py-2 px-4 rounded inline-flex items-center">
            Go Back
        </a>
    </div>
</div>
{% endblock %}