src/canary/urls.py
from django.urls import path

from . import views

app_name = "canary"
urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login, name="login"),
    path("dashboard/", views.dashboard, name="dashboard"),

    # urls for notifications
    path("notifications/", views.notifications, name="notifications"),
    path("clear_all_notifications/", views.clear_all_notifications, name="clear_all_notifications"),
    path("delete_notification/", views.delete_notification, name="delete_notification"),
]

src/communities/urls.py
from django.urls import path, re_path
from . import views

app_name = "communities"
urlpatterns = [
    path("create_community/", views.create_community, name="create_community"),
    path("save_community", views.save_community, name="save_community"),
    #path("edit_community/", views.edit_community_redirect, name="edit_community_redirect"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/edit_community/$", views.edit_community_redirect, name="edit_community_redirect"),

    path("edit_community/submit", views.edit_community, name='edit_community'),

    #path("leave_community/", views.leave_community, name="leave_community"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/leave_community/$", views.leave_community, name="leave_community"),


    re_path(r"^(?P<community_id>[0-9a-f-]+)/dashboard/$", views.community_dashboard, name="dashboard"),

    # community joining / leaving
    path("join_community_error/<str:error_type>/", views.join_community_error, name="join_community_error"),
    path("join_success/", views.join_success, name="join_success"),

    # special url for invite links
    re_path(r"^generate_invite/(?P<community_id>[0-9a-f-]+)/$", views.generate_invite_link, name="generate_invite"),
    re_path(r"^invite/(?P<token>[0-9a-f-]+)/$", views.join_community_by_invite, name="join_community_by_invite"),

    # url for submitting anonymously through a link
    re_path(r"^(?P<token>[0-9a-f-]+)/anon_report/", views.create_anonymous_report, name="create_anonymous_report"),

    # urls for report management
    re_path(r"^(?P<community_id>[0-9a-f-]+)/create_report/", views.create_report, name="create_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/save_report/", views.save_report, name="save_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/report/(?P<report_id>[0-9a-f-]+)/$", views.view_report, name="view_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/report/(?P<report_id>[0-9a-f-]+)/edit/", views.edit_report, name="edit_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/report/(?P<report_id>[0-9a-f-]+)/delete/", views.delete_report, name="delete_report"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/change_admin_status/(?P<member_id>[0-9a-f-]+)/", views.change_admin_status,
            name="change_admin_status"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/remove_member/(?P<member_id>[0-9a-f-]+)/", views.remove_member,
            name="remove_member"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/community_members/", views.community_members, name="community_members"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/make_owner/(?P<member_id>[0-9a-f-]+)/", views.make_owner, name="make_owner"),
    re_path(r"^(?P<community_id>[0-9a-f-]+)/save_owner/(?P<member_id>[0-9a-f-]+)/", views.save_owner, name="save_owner"),

]

src/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('canary.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('accounts/', include('accounts.urls')),   
    path('community/', include('communities.urls')),
]

src/communities/models.py
from django.db import models
import uuid
from django.utils import timezone
from django.contrib.auth import get_user_model
# Create your models here.


# main community model
class Community(models.Model):
    #class Meta:
        #app_label = 'communities'

    # each community has a unique id
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)

    description = models.TextField(blank=False, max_length=500)

    # each community stores a list of reports submitted to that community
    reports = models.ManyToManyField('Report')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

# invite link model
class InviteLink(models.Model):
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    token = models.UUIDField(default=uuid.uuid4, editable=False)
    expiration_time = models.DateTimeField()
    # max uses for link, 0 means unlimited
    max_uses = models.IntegerField(default=0)
    used_count = models.IntegerField(default=0)
    link_type = models.CharField(max_length=4, default='join') # join or anon for now

    def is_valid(self):
        return (self.used_count < self.max_uses or self.max_uses == 0) and self.expiration_time > timezone.now()

# community member relational model
class CommunityMember(models.Model):
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    member = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    is_admin = models.BooleanField(default=False)
    is_owner = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.member} in {self.community}'

# --- REPORT MODELS ----

# report model
class Report(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100, blank=False)
    content = models.TextField(max_length=2000, blank=True)

    # the author user is optional (for anonymous reports)
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True)

    # users can specify how the report is handled from a few options
    class ResolutionMethod(models.TextChoices):
        CANARY = 'CAN', 'Canary'
        EXTERNALLY = 'EXT', 'Externally'
        NO_CONTACT = 'NOC', 'No Contact'

    resolution_method = models.CharField(
        max_length=3,
        choices=ResolutionMethod.choices,
        default=ResolutionMethod.CANARY,
    )

    # reports have a status, either "New", "In Progress", or "Resolved"
    class Status(models.TextChoices):
        NEW = 'NEW', 'New'
        IN_PROGRESS = 'INP', 'In Progress'
        RESOLVED = 'RES', 'Resolved'

    status = models.CharField(
        max_length=3,
        choices=Status.choices,
        default=Status.NEW,
    )

    # reports have a large text field for notes added by an admin
    notes = models.TextField(blank=True, max_length=2000)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title


class UploadedFile(models.Model):
    file = models.FileField(upload_to='uploads/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    # each file is associated with a report
    report = models.ForeignKey(Report, on_delete=models.CASCADE)

    def __str__(self):
        return self.file.name

src/templates/report/create_report.html
{% extends "base.html" %}
{% block breadcrumb %}
<nav class="flex py-3 px-5 text-gray-700 bg-gray-600 shadow-lg" aria-label="Breadcrumb">
    <ol class="inline-flex items-center space-x-1 md:space-x-3">
        <li class="inline-flex items-center">
            <a href="{% url 'canary:home' %}"
                class="inline-flex items-center text-sm font-medium text-white hover:text-gray-200">
                <svg aria-hidden="true" class="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z">
                    </path>
                </svg>
                Home
            </a>
        </li>
        <li>
            <div class="flex items-center">
                <svg aria-hidden="true" class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                        clip-rule="evenodd"></path>
                </svg>
                <a href="{% url 'canary:dashboard' %}"
                    class="ml-1 text-sm font-medium text-white hover:text-gray-200 md:ml-2">User Dashboard</a>
            </div>
        </li>
        <li>
            <div class="flex items-center">
                <svg aria-hidden="true" class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                        clip-rule="evenodd"></path>
                </svg>
                <a href="{% url 'communities:dashboard' community_id %}"
                    class="ml-1 text-sm font-medium text-indigo-400 hover:text-gray-200 md:ml-2">Community Dashboard</a>
            </div>
        </li>
    </ol>
</nav>
{% endblock breadcrumb %}
{% block content %}
<div class="bg-gray-900 mt-4 flex items-center justify-center">
    <div class="w-full max-w-4xl bg-gray-800 shadow-md rounded-lg overflow-hidden">
        <div class="p-8">
            <h2 class="text-2xl font-bold text-gray-100 mb-6">Create a New Report</h2>
            <form method="post" action="{% url 'communities:save_report' community_id %}" enctype="multipart/form-data"
                class="space-y-4">
                {% csrf_token %}
                <div>
                    <label for="title" class="block text-white font-bold mb-2">Title:</label>
                    <input type="text"
                        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-300 bg-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-opacity-50"
                        id="title" name="title" required>
                </div>
                <div>
                    <label for="content" class="block text-white font-bold mb-2">Content:</label>
                    <textarea
                        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-300 bg-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-opacity-50"
                        id="content" name="content" rows="5" required></textarea>
                </div>
                <div>
                    <label for="resolution_method" class="block text-white font-bold mb-2">Resolution Method:</label>
                    <select
                        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-300 bg-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-opacity-50"
                        id="resolution_method" name="resolution_method" required>
                        <option value="CAN" selected>Canary</option>
                        <option value="EXT">Externally</option>
                        <option value="NOC">No Contact</option>
                    </select>
                </div>
                <div>
                    <label for="media" class="block text-white font-bold mb-2">Media Files (optional):</label>
                    <input type="file"
                        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-300 bg-gray-700 leading-tight focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-opacity-50"
                        id="media" name="media" multiple>
                </div>
                <!-- anonymous checkbox -->
                <div class="gap-2 flex items-center">
                    <input type="checkbox" id="anonymous" name="anonymous"
                        class="w-4 h-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded">
                    <label for="anonymous" class="block text-white font-bold ">Submit Anonymously</label>
                </div>
                <div class="flex gap-2">
                    <a href="{% url 'communities:dashboard' community_id %}"
                        class="bg-indigo-400 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-opacity-50 transition duration-150 ease-in-out inline-block">
                        Go Back
                    </a>
                    <button type="submit"
                        class="bg-indigo-400 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-opacity-50 transition duration-150 ease-in-out">
                        Submit Report
                    </button>
                </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}

src/templates/report/view_report.html
{% extends "base.html" %}
{% load static %}
{% block breadcrumb %}
<nav class="flex py-3 px-5 text-gray-700 bg-gray-600 shadow-lg" aria-label="Breadcrumb">
    <ol class="inline-flex items-center space-x-1 md:space-x-3">
        <li class="inline-flex items-center">
            <a href="{% url 'canary:home' %}"
                class="inline-flex items-center text-sm font-medium text-white hover:text-gray-200">
                <svg aria-hidden="true" class="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z">
                    </path>
                </svg>
                Home
            </a>
        </li>
        <li>
            <div class="flex items-center">
                <svg aria-hidden="true" class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                        clip-rule="evenodd"></path>
                </svg>
                <a href="{% url 'canary:dashboard' %}"
                    class="ml-1 text-sm font-medium text-white hover:text-gray-200 md:ml-2">User Dashboard</a>
            </div>
        </li>
        <li>
            <div class="flex items-center">
                <svg aria-hidden="true" class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                        clip-rule="evenodd"></path>
                </svg>
                <a href="{% url 'communities:dashboard' community_id %}"
                    class="ml-1 text-sm font-medium text-indigo-400 hover:text-gray-200 md:ml-2">Community Dashboard</a>
            </div>
        </li>
    </ol>
</nav>
{% endblock breadcrumb %}
{% block content %}
    <div class="bg-gray-900 mt-4 flex items-center justify-center">
        <div class="w-full max-w-4xl bg-gray-800 shadow-md rounded-lg overflow-hidden">
            <div class="p-8">
                <div class="flex justify-between items-center mb-6">
                    <h2 class="text-2xl font-bold text-gray-100">{{ report.title }}</h2>
                    {% if is_admin %}
                        <form method="post"
                              action="{% url 'communities:edit_report' community.id report.id %}">
                            {% csrf_token %}
                            <select name="status"
                                    class="py-2 px-3 text-gray-300 bg-gray-700 border-gray-600 rounded-md focus:border-indigo-500 focus:ring focus:ring-indigo-500 focus:ring-opacity-50">
                                {% for status in report.Status.choices %}
                                    <option value="{{ status.0 }}"
                                            {% if report.status == status.0 %}selected{% endif %}>
                                        {{ status.1 }}
                                    </option>
                                {% endfor %}
                            </select>
                            <button type="submit"
                                    class="bg-indigo-400 text-white px-4 py-2 rounded-md hover:bg-indigo-600 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-opacity-50 transition duration-150 ease-in-out ml-4">
                                Update
                            </button>
                        </form>
                    {% else %}
                        <span class="px-3 py-1 rounded-full text-xs font-medium {% if report.status == 'open' %}bg-green-500 text-white{% elif report.status == 'in_progress' %}bg-yellow-500 text-white{% else %}bg-red-500 text-white{% endif %}">
                            {{ report.get_status_display }}
                        </span>
                    {% endif %}
                </div>
                <p class="text-gray-300 mb-6">{{ report.content }}</p>
                <div class="bg-gray-700 rounded-lg p-4 mb-6">
                    <h6 class="text-lg font-semibold text-gray-100 mb-2">Report Details</h6>
                    <div class="grid grid-cols-2 gap-4">
                        <div>
                            <p class="text-gray-400 mb-1">Resolution Method:</p>
                            <p class="text-gray-300">{{ report.get_resolution_method_display }}</p>
                        </div>
                        {% if report.author %}
                            <div>
                                <p class="text-gray-400 mb-1">Submitted by:</p>
                                <p class="text-gray-300">{{ report.author }} ({{ report.author.email }})</p>
                            </div>
                        {% else %}
                            <div>
                                <p class="text-gray-400 mb-1">Submitted:</p>
                                <p class="text-gray-300">Anonymously</p>
                            </div>
                        {% endif %}
                        <div>
                            <p class="text-gray-400 mb-1">Created at:</p>
                            <p class="text-gray-300">{{ report.created_at }}</p>
                        </div>
                        <div>
                            <p class="text-gray-400 mb-1">Updated at:</p>
                            <p class="text-gray-300">{{ report.updated_at }}</p>
                        </div>
                    </div>
                </div>
                <h6 class="text-lg font-semibold text-gray-100 mb-2">Media Files:</h6>
                {% if media %}
                    <div class="grid grid-cols-2 md:grid-cols-3 gap-4 mb-6">
                        {% for media_file in media %}
                            <div class="bg-gray-700 rounded-lg p-4">
                                <a href="{{ media_file.file.url }}"
                                   target="_blank"
                                   class="text-indigo-500 hover:text-indigo-400">{{ media_file.file.name  | slice:"8:" }}</a>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <p class="text-gray-300 mb-6">No media files attached to this report.</p>
                {% endif %}
                <div class="bg-gray-700 rounded-lg p-4">
                    <h6 class="text-lg font-semibold text-gray-100 mb-2">Response</h6>
                    {% if is_admin %}
                        <form method="post"
                              action="{% url 'communities:edit_report' community.id report.id %}"
                              class="mt-2">
                            {% csrf_token %}
                            <textarea name="notes"
                                      class="w-full h-40 border border-gray-600 rounded-md px-4 py-2 resize-none bg-gray-800 text-gray-300 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-opacity-50"
                                      placeholder="Enter notes here...">{{ report.notes }}</textarea>
                            <button type="submit"
                                    class="mt-3 bg-indigo-400 text-white px-4 py-2 rounded-md hover:bg-indigo-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                Reply to Report
                            </button>
                        </form>
                    {% else %}
                        <p class="text-gray-300">{{ report.notes }}</p>
                    {% endif %}
                </div>
                <div class="flex justify-between items-center mt-6">
                    <a href="{% url 'communities:dashboard' community.id %}"
                       class="bg-gray-700 text-gray-100 font-bold py-2 px-4 rounded hover:bg-gray-600 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-opacity-50 transition duration-150 ease-in-out">Back
                    to Community</a>
                    {% if is_admin %}
                        <div class="flex space-x-2">

                            <a href="{% url 'communities:delete_report' community.id report.id %}"
                               class="bg-red-500 text-white font-bold py-2 px-4 rounded hover:bg-red-600 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-opacity-50 transition duration-150 ease-in-out">Close
                            Report</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}